Repository iNZightVIT/iNZightPlots, pull requests merged in 2019-08, with the labels that each got.

#124 Add rotation ability for gridplots
  NEWS.Md
  R/iNZGG.R
Labels: bug, enhancement

#127 Provide a simple summary for date/time data
  DESCRIPTION
  NEWS.Md
  R/drawAxes.R
  R/inzDataframe.R
  R/summary.R
  tests/testthat/test_datetimes.R
Labels: bug, enhancement

#131 Feature/hyp test proportions
  NEWS.Md
  R/inference.R
  tests/testthat/test_inference.R
Labels: enhancement

#132 Show simulated p-value on chi-square inference
  R/getSummary.R
  R/inference.R
  man/getPlotSummary.Rd
  tests/testthat/test_inference.R
Labels: enhancement

#139 Disable boxplots in exported plots if checkbox is unchecked
  NEWS.Md
  R/exportHTML.R
  inst/dpsp.js
  inst/histogram.js
Labels: bug

#140 Replace prop.test with manual z-score + normal approximation
  R/inference.R
  tests/testthat/test_inference.R
Labels: enhancement
