Repository iNZightVIT/iNZightPlots, pull requests merged in 2020-05, with the labels that each got.

#204 Feature/svy design effects
  NAMESPACE
  NEWS.Md
  R/getSummary.R
  R/iNZightPlot.R
  R/inference.R
  R/summary.R
  man/getPlotSummary.Rd
  tests/testthat/test_survey.R
Labels: enhancement

#209 Bugfix/barplot yaxis labs
  NEWS.Md
  R/drawAxes.R
  R/iNZightPlot.R
  tests/testthat/test_bar.R
Labels: bug

#211 Fix #105
  R/iNZGG.R
  tests/testthat/test_ftplots.R
Labels: enhancement

#212 Move interactive map polygon function and remove sf dep
  DESCRIPTION
  R/exportHTML.R
Labels: enhancement

#210 Release/2.11.5
  .travis.yml
  DESCRIPTION
  NAMESPACE
  NEWS.Md
  R/colourpalettes.R
  R/createPlot.R
  R/drawAxes.R
  R/exploreAllPlots.R
  R/exploreAllSummaries.R
  R/exportHTML.R
  R/exportSVG.R
  R/general.R
  R/getSummary.R
  R/iNZGG.R
  R/iNZightPlot.R
  R/inference.R
  R/inzpar.R
  R/makeTitles.R
  R/parameters.R
  R/summary.R
  cran-comments.md
  inst/maps.js
  man/can.interact.Rd
  man/const_palette_names.Rd
  man/convert.to.factor.Rd
  man/create.Rd
  man/emphasize_pal_colour.Rd
  man/exploreAllPlots.Rd
  man/exploreAllSummaries.Rd
  man/exportHTML.Rd
  man/getPlotSummary.Rd
  man/iNZightPlot.Rd
  man/inzpalette.Rd
  man/inzpar.Rd
  tests/testthat/test_bar.R
  tests/testthat/test_ftplots.R
  tests/testthat/test_palettes.R
  tests/testthat/test_survey.R
Labels: release
